name: Bug report
title: "[Bug] Bug title "
description: If something isn't working as expected.
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        For better global communication, Please write in English.

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the [issues](https://github.com/Bannirui/orm-generator/issues?q=is%3Aissue)
        first to see whether the same issue was reported already.
      options:
        - label: >
            I had searched in the [issues](https://github.com/Bannirui/orm-generator/issues?q=is%3Aissue) and found
            no similar issues.
          required: true

  - type: dropdown
    attributes:
      label: Environment
      description: Describe the environment.
      options:
        - Mac
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: dropdown
    attributes:
      label: orm-generator version
      description: Describe the orm-generator version.
      options:
        - master
        - 1.0.2
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: What happened
      description: Describe what happened.
      placeholder: >
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce
      description: >
        Describe the steps to reproduce the bug here.
      placeholder: >
        Please make sure you provide a reproducible step-by-step case of how to reproduce the problem
        as minimally and precisely as possible.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Debug logs
      description: Anything else we need to know?
      placeholder: >
        Add your debug logs here.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Are you willing to submit PR?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
        especially if you already have a good understanding of how to implement the fix.
      options:
        - label: Yes I am willing to submit a PR!

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: >
        The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it..
      options:
        - label: I agree to follow this project's [Code of Conduct](https://www.gnu.org/licenses/gpl-3.0.html) *

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"