name: Documentation Related
title: "[Doc] Documentation Related "
description: I find some issues related to the documentation.
labels: [ "documentation" ]
body:
  - type: markdown
    attributes:
      value: |
        For better global communication, Please write in English.

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the [issues](https://github.com/Bannirui/orm-generator/issues?q=is%3Aissue)
        first to see whether the same issue was reported already.
      options:
        - label: >
            I had searched in the [issues](https://github.com/Bannirui/orm-generator/issues?q=is%3Aissue) and found
            no similar issues.
          required: true

  - type: textarea
    attributes:
      label: Documentation Related
      description: Describe the suggestion about document.
      placeholder: >
        e.g There is a typo
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Are you willing to submit PR?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
        especially if you already have a good understanding of how to implement the fix.
      options:
        - label: Yes I am willing to submit a PR!

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: >
        The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it..
      options:
        - label: I agree to follow this project's [Code of Conduct](https://www.gnu.org/licenses/gpl-3.0.html) *

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"