name: Unit Test
title: "[Unit Test] Unit test title"
description: I want to do some unit tests for this project
labels: [ "testing" ]
body:
  - type: markdown
    attributes:
      value: |
        For better global communication, Please write in English.

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the [issues](https://github.com/Bannirui/orm-generator/issues?q=is%3Aissue)
        first to see whether the same issue was reported already.
      options:
        - label: >
            I had searched in the [issues](https://github.com/Bannirui/orm-generator/issues?q=is%3Aissue) and found
            no similar issues.
          required: true

  - type: textarea
    attributes:
      label: Unit test request
      description: Describe the unit test.
      placeholder: >
        First of all: Have you checked GitHub issues whether someone else has already reported your issue?
        Maybe the unit tests you want to do have already been done?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the unit tests you want to do
      description: Describe the unit test.
      value: |
        Module name:
        Located at:
        Task status: ×(unfinished) / √(finished)
        | Task Status | Class | Type |
        | :------: | :------ | :------ |
        | × | xxxxxx | xxxxxx |
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Are you willing to submit PR?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
        especially if you already have a good understanding of how to implement the fix.
      options:
        - label: Yes I am willing to submit a PR!

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"